version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.11
  - dependency-name: electron-rebuild
    versions:
    - 2.3.4
  - dependency-name: electron-updater
    versions:
    - 4.3.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
